log4js-node/log4js-node

lib/log4js.js
if `cwd` is included in option, reload will not work
=> add options to reload function

lib/layouts.js, test/layouts-test.js
Metadata for users such as name, email, etc are not always present for users.  For example, I am running express and I want to log the %x{company}%x{username} so that when I look at my logs I can immediately understand which user this affects.  Or for example, I could log %x{payingOrTial} the type of user.  
This works well when the user is logged in.  However, my logger encompasses everything.  I log when the server boots up.  I log during the login screen where a user is not yet logged in.  In these circumstances there is no way to retrieve this metadata.
So for example
```
"username": function () {
var session = require('continuation-local-storage').getNamespace('api.callinize');
if(!session) session = require('continuation-local-storage').getNamespace('dashboard.callinize');
var …
```
=> Allow for blank tokens due to dynamic data

lib/log4js.js
modified:   lib/log4js.js
Please refer to  [How to use with Browserify?](https://github.com/nomiddlename/log4js-node/issues/263) 
I do not know if this change is necessary, or if a better method is already known.
I am using my own copy in the meantime with this clause in the package.json of my project : 
"dependencies": {
"private-log4js": "git+ssh://git@github.com:FleetingClouds/log4js-node.git",
}
If you too are noob, trying to figure all this out, I've made a bare minimum example of how I did it : [Baby Steps](https://github.com/FleetingClouds/javascript-bdd-baby-steps/tree/master/Browserify)
=> Force bundling of appenders/console

lib/appenders/clustered.js, lib/layouts.js
I modified the clustered appender so it will add the original process identifier as well as an object containing cluster metadata.
I then modified the layouts.js file, first by rewriting the pid() function which will preferably use the loggingEvent.pid variable so that the log message will have the appropriate PID attached to it. I then implemented a new function, clusterInfo(), which allows you to write cluster-specific meta-data if available, with support for a custom pattern.
I'm not familiar with the unit-testing framework, hence no tests, but they should be pretty straight-forward.
=> added cluster identifier support

lib/appenders/file.js, lib/levels.js, lib/log4js.js, lib/logger.js, lib/streams/BaseRollingFileStream.js, lib/streams/RollingFileStream.js, test/fileAppender-test.js, test/levels-test.js, test/subcategories-test.js
Hi!
I had to add some features to log4js at my work and I thought those could be of interest. I added:
* subcategories: this allows to set a level for a major category then specify other levels for sub-categories. For example:
"levels": {
"cat": "WARN",
"cat.sub1": "TRACE",
"cat.sub1.sub12": "WARN",
"cat.sub3": "INFO"
}
If not specified, a sub-category inherits the level of its parent. Given the example configuration above, a logger with category "cat.sub4" would have level "WARN", inherited from category "cat". The appenders  also accept sub-categories, they will log the category and all sub-categories specified at their configurations. So, it is possible to create a logger only for category "cat.sub1.sub12".
* a level property at the file appender: this allows to restrict the levels …
=> Vivocha 0.6.20

lib/connect-logger.js, package.json, test/connect-logger-test.js
The connect logger comes with a pre-defined family of tokens that can be used in its log string formats (e.g. `:url`, `:method`). This pull request extends the connect-logger to allow custom tokens (`arbitrary_string` or regexp) to be defined and used in the logger format.
Custom tokens are passed in and referred to in the `connectLogger` call like so:
```javascript
log4js.connectLogger(logger4js_logger, { format: ':method :custom', tokens: [{
token: ':custom',
replacement: 'this is not a very useful custom token'
}] });
```
If a custom token is the same as one of the default tokens (`:date`, `:response-time` etc) then the default token is overridden.
Some of the files had trailing whitespace which Sublime removed before I realised it - I've tried to separate those changes into separate …
=> Custom connect tokens

lib/appenders/console.js, lib/appenders/dateFile.js, lib/appenders/file.js, lib/appenders/fileSync.js, lib/appenders/smtp.js, lib/date_format.js, lib/layouts.js, test/date_format-test.js, test/layouts-test.js
Often enough remote servers have either diverging or irrelevant timezone settings (from the operation team point of view at least)
In order to display a relevant timestamp in the log, this PR implements an appender-level setting for timezone offset.
The impact is mostly on the prototype of layout that get an extra parameter for timezoneOffset.
The code assumes backward compatible behavior when such configuration is missing.
The following appenders have been modified:
* console
* dateFile
* file
* fileSync
* SMTP
Usage is as simple as adding a timezoneOffset to the appender configuration.
I am not too happy with some workarounds I had to use to get the unit tests to pass, but the original injection of getTimezoneOffset to override the default behavior was pretty hackish from the beginning …
=> Add appender-level timezone offset config

lib/appenders/gelf.js, test/gelfAppender-test.js
While trying to set custom per-message fields via logging with the GELF appender, I noticed that logstash was dropping the message when the GELF flag was set. Still not 100% sure why, but a simple fix for me was to delete the GELF flag after it was checked (seen in this PR), and everything seemed to work happily.
TLDR sort of
* Logstash (which supports GELF) drops messages with the GELF flag present
* There's no particular need to keep this key besides telling the appender to set custom feilds
Hopefully I can merge this in, it seemed like overkill to mimic this appender for logstash with such a minor change.
=> Remove GELF flag when capturing custom fields

lib/appenders/smtp.js, test/smtpAppender-test.js
With this change you can use the various nodemailer transport plugins by adding a transport key to your appender config:
```javascript
{
"appenders": [ {
"type": "smtp",
"recipients": "user@domain.com",
"transport": {
"plugin": "sendmail",
"options": {
"path": "/usr/sbin/sendmail",
"args": [ "-t", "-oi", "-oem" ]
}
}
}]
}
```
=> Feature - Add support for nodemailer transport plugins

lib/appenders/clustered.js, test/clusteredAppender-test.js
When logging an `Error` object using the clustered appender, the logged event is a JSON representation of the error, ex:
[2015-06-09 11:13:48.257] [ERROR] middleware.Security - { stack: 'Error: User is not authorized\n at Object.exec (D:\\Borealis\\demoux\\IMS\\server\\IMS\\middleware\\SecurityCheck\\Instance.js:41:14)\n [...] at applyArgs (D:\\Borealis\\demoux\\IMS\\server\\node_modules\\flow\\flow.js:9:15)\n at Function.flowState (D:\\Borealis\\demoux\\IMS\\server\\node_modules\\flow\\flow.js:39:6)\n at applyArgs (D:\\Borealis\\demoux\\IMS\\server\\node_modules\\flow\\flow.js:9:15)\n at Function.thisFlow.exec (D:\\Borealis\\demoux\\IMS\\server\\node_modules\\flow\\flow.js:94:4)\n at applyArgs (D:\\Borealis\\demoux\\IMS\\server\\node_modules\\flow\\flow.js:9:15)\n at thisFlow …
=> clustered appender - Unwrap the serialized errors

lib/appenders/logstashUDP.js, test/logstashUDP-test.js
Current logstashUDP appender doesn't send category of the loggingEvent which is very useful when filtering for logs.
=> Add missing category field

.gitignore, lib/appenders/smtp.js, package.json, test/smtpAppender-test.js
Please find attached a patch for log4js SMTP appender that allows to send an email with remaining logs when shutdown method is called. This is useful when we want a one-shot email when a program ending and don't wait the timeout.
Other small changes (out of appender scope) :
- Show process details when vows is launched;
- Ignore other generated temporary files with pattern test/streams/test-*
=> Send a remaining logs email when shutdown is called

lib/appenders/dateFile.js, lib/appenders/file.js, lib/log4js.js
Bug in https://github.com/nomiddlename/log4js-node/pull/345, `N.shutdown` currently never calls its callback in a few cases:
1. When no appenders with shutdown functions are loaded (for example, we're in a worker with only `clustered` appender loaded), the amount of shutdown functions is zero. So callback is never called 'cause it waits for a finish of at least one shutdown function.
2. When file appender is loaded, but not actually used, an amount of open files is zero. Same thing, callback is never called.
Same for dateFile apparently, although I didn't test that.
// cc: @hmalphettes
=> fix shutdown callbacks not being called

lib/appenders/loggly.js, test/logglyAppender-test.js
This appender allows adding tags to any call to the logger.
Documentation added:
Loggly Tagged Appender. Sends tagged logging events to Loggly using node-loggly.
The difference with the Loggly appender is that this appender will scan the msg from the
logging event, and pull out any argument of the shape `{ tags: [] }` so that it's possible
to add tags in a normal logging call. For example:
logger.info({ tags: ['my-tag-1', 'my-tag-2'] }, 'Some message', someObj, ...)
And then this appender will remove the tags param and append it to the config.tags.
=> Add new appender logglyTagged

README.md, lib/appenders/stderr.js, test/stderrAppender-test.js
Thus functions almost identically to the consoleAppender except that
instead of logging through `console.log` it uses `process.stderr.write`.
This is useful in cases where applications include their own console
output to stdout but want to have debug / error logs that go to stderr
so users can potentially redirect to separate out the logs from the output.
=> add a stderr appender

examples/hipchat-appender.js, lib/appenders/hipchat.js, test/hipchatAppender-test.js
v1 is _very_ deprecated. lets switch to  [hipchat-notifier](https://github.com/briceburg/hipchat-notifier) library to use apiv2 and simplify. 
+1 allows named rooms
+1 is not deprecated
+1 allows configurable layout (e.g. for sending HipChat cards)
closes https://github.com/BlueAcornInc/log4js-node/issues/2
=> use HipChat apiv2 in hipchat appender

README.md, lib/levels.js, lib/log4js.js, lib/logger.js, package.json, test/newLevel-test.js
Have added additionally functionality to create custom log levels not already defined in `log4js-node` which has been brought up in #276, following the log4j2 [linked](http://logging.apache.org/log4j/2.x/manual/customloglevels.html). Have hoped to close out this feature request.
=> Custom levels

lib/connect-logger.js
restify uses req.url to denote the invoked url path for http, this change allows to make the logger connect work with restify out of the box
=> add req.url so that connect works with restify

lib/layouts.js, lib/logger.js
Allow V8 to optimize functions by not [leaking the arguments object](https://github.com/petkaantonov/bluebird/wiki/Optimization-killers#32-leaking-arguments).
This results in a performance improvement of about 20%.
before: 28,566 ops/sec ±2.27% (82 runs sampled)
after: 34,305 ops/sec ±1.96% (87 runs sampled)
Improvement: ~20%
``` js
'use strict';
const Benchmark = require('benchmark');
const log4js = require('log4js');
log4js.configure({
appenders: [
{type: 'file', filename: 'log4jsbench.log', category: 'bench'},
],
levels: {
bench: 'debug',
},
});
const logger = log4js.getLogger('bench');
const data = {a: 'thing', num: 2};
new Benchmark.Suite()
.add('log', function() {
logger.info('message', data);
})
.on('cycle', function(event) {
console.log(String(event.target));
})
.run();
```
=> Improve core logging performance

lib/date_format.js, test/vows/date_format-test.js, test/vows/layouts-test.js
Without milliseconds, the output of the log when sent to log collector, such as Logstash or Kibana, are not useful. Because Kibana uses the timestamp to sort the log, then the order of the log not always display correctly within one second.
=> fix for #315 - Include milliseconds in format ISO8601_WITH_TZ_OFFSET

lib/appenders/logstashUDP.js, test/tap/logstashUDP-test.js
I was trying to create a more consistent way of creating fields by removing the "field" and the dot for LogstashUDP. For some reason, Logstash 5.1 mutate does not process any fields with a "." in it's field.
=> feat(LogstashUDP): Added a way for fields to be added without dot.

lib/appenders/dateFile.js, lib/appenders/file.js, test/tap/dateFileAppender-test.js, test/tap/fileAppender-test.js
The current file appender `shutdown` functions don't actually work properly.
`write` is fully asynchronous whether it returns true or false, so we can't just `end` the stream immediately - this causes a "write after end" error.
I think the right thing to do here is to write an empty string and wait for the callback to trigger. Since writes are sequential and logging gets disabled prior to shutdown, this should ensure that any earlier writes have already occurred.
In addition, I don't think we actually need the draining logic - if `write` returns false, the data is still buffered and written. It's just a signal to the caller that any further writes should wait for a drain, which is irrelevant here since this is the last thing we're going to be writing.
Added a unit test - this test fails …
=> Properly flush file appenders on shutdown

lib/layouts.js
bugfix for issue #457 "pattern %z (process id) can not be padded/truncated"
see https://github.com/nomiddlename/log4js-node/issues/457
=> bugfix for issue #457

docs/file.md
`maxLogSize` is 10Mb in the description below.
However, 10,458,760 bytes is 9.97425079346 Mb.
=> docs(file): fix maxLogSize

docs/api.md, docs/faq.md, examples/pm2.js, lib/appenders/recording.js, lib/configuration.js, lib/log4js.js, test/tap/cluster-test.js, test/tap/configuration-validation-test.js, test/tap/multiprocess-shutdown-test.js, test/tap/pm2-support-test.js
This fixes #265 - users will also need to install the pm2 module `pm2-intercom`, and add `pm2: true` to their log4js config.
=> PM2 Support

lib/appenders/logstashUDP.js
Fixed an issue that was introduced in commit 6746e2e0488f3c900fd358af0a50d4795df65de7
All fields became sticky, so each time a field was sent via a message, it showed up in all messages after that
=> fix: sticky fields

docs/migration-guide.md
but 'task' does. This tripped us up while migrating an older project using this library.
=> In the above example 'tasks' does not exist

types/log4js.d.ts
Missing return types on functions causes the compiler to fail
when using the `strict` or `noImplicitAny` TypeScript flags.
=> Add return types for addLayout() and shutdown() functions.

docs/logstashUDP.md, lib/appenders/logstashUDP.js, test/tap/logstashUDP-test.js
Added a config option called args, to determine how to log args:
both (default for backward compatibility): under the fields property and as direct properties of the log object.
fields: only under the fields property.
direct: only as direct propertiesd of the log object.
=> feat(logstashUDP): Added args config option

types/log4js.d.ts
Logger no longer has a `setLevel` method.
=> fix: Remove setLevel from Logger TypeScript definition

docs/logstashUDP.md, lib/appenders/logstashUDP.js, test/tap/logstashUDP-test.js
Support dynamic field values, by allowing configured fields to be functions.
This code is essentially copied from the pattern layout where this functionality already exists.
It may be desirable to add it to other JSON based appenders as well.
Including the appropriate test in the logStashUDP-test and the updated documentation.
=> feat(logstashUDP): Added ability to have dynamic fields

lib/appenders/multiprocess.js, lib/log4js.js, package.json, test/tap/cluster-test.js
This is a fix for #523 - uses circular-json to handle circular references. As circular-json has a custom format for JSON, I haven't included these changes in the GELF, logFaces or logstash appenders as the things listening on the other end won't know what to do with it.
=> fix(cluster): added circular json dep

lib/log4js.js, test/tap/configuration-test.js
logger will be configured either by user or at first call to getLogger.
According to documentation `If you do not call configure, log4js will use LOG4JS_CONFIG (if defined) or the default config.`
That is currently not the case as configure is called at module load time no matter if/when client code calls the configure.
This PR aims to fix this behavior.
Reasoning: we are using webpack for server packing and due to dynamic loading of appenders, these are not included in the final package (the suggestions in several bug reports don't work either).
In our project I would like to override the loading behavior to address the issue, but call to configure with the default config already tries to load the stdout which is not in the bundle and fails.
This PR preserves the original behavior …
=> fix: deferred logger configuration.

package.json
Currently, `log4js-node` installs the entire project when being `npm install`ed. This is an anti-pattern, and it leads to a package almost 1MB larger than it needs to be, as it includes the entire set of docs every time it gets installed (among other things.)
This PR reduces the size of the `npm install`ed packaged to ~100KB by only including the bits that are `log4js`. This makes the project easier to used in constrained environments.
More details: https://docs.npmjs.com/files/package.json#files
=> Use the "files" property to only include the `lib` folder when `npm install`ing

lib/log4js.js, test/tap/levels-before-configure-test.js
This fixes the problem of trying to use levels before configure has been called (either explicitly or by the first call to `getLogger`). This was a change introduced by #648. The only problem with this fix is that the references to levels and connectLogger will be invalid after configure is called - but they will only be functionally different if there have been custom levels defined. And if you're defining custom levels in your config then you probably want to call configure before accessing levels anyway.
=> fix(#652): access levels before configure is called

lib/appenders/redis.js, test/tap/redisAppender-test.js
This closes the `redisClient` connection upon `log4js.shutdown()`, allowing the process to exit cleanly.  Otherwise I found the redis connection prevents the process from exiting and effectively "hangs"
Let me know if you see any problems or would like me to make changes.
Thank you for an excellent project.
-Ben
=> feat(redis): quit on log4js.shutdown

docs/api.md, lib/log4js.js, test/tap/configuration-test.js, types/log4js.d.ts, types/test.ts
The changes within this PR allow to write code like:
```javascript
const log = require('log4js').configure(conf).getLogger('daemon');
```
For this PR I have:
1. Added `return` statement for log4js.configure(...) method.
2. Refactored the `configuration-test.js` file.
3. Added new test to `configuration-test.js` file. This test checks  the value, returned by `log4js.configure(...)` method.
4. Appended the `configure(...)` related article in the docs.
=> Configure method for oneliners

package-lock.json, package.json, types/log4js.d.ts, types/test.ts, types/tsconfig.json
* Strictly type the exported Log4js interface.
* Test the typings for strictness using the TypesScript compiler.
The PR addresses #709.
A few things to note:
* I did not see a preferred version of npm to use when installing new dependencies. I use version `5.6.0` which makes some significant changes to the checked-in _package-lock.json_. If you'd prefer a different version of npm to tamp down those changes, I'd be happy to use it and squash the history.
* I added TypeScript as a dev dependency and an npm script to test the typings, but I did not prescribe how that script runs automatically. If you'd like to see that in prepush or elsewhere I can make that change.
=> fix(#709): strict Log4js typings

lib/appender-adapter.js, lib/configuration.js, test/tap/fileAppender-test.js, test/tap/fileSyncAppender-test.js, types/log4js.d.ts
enable maxLogSize with unit: '1K', '1M', '1G'. like 
```
appenders: {
app: { type: 'file', filename: 'logs/app.log', maxLogSize: '100K', backups: 3 }
}
```
supports the feature in #352 
add tests in fileAppender-test.js and fileSyncAppender-test.js
=> feat: Enable maxLogSize with unit

lib/appenders/multiprocess.js, test/tap/multiprocess-shutdown-test.js, test/tap/multiprocess-test.js, test/tap/multiprocess-worker.js
Handle the `'error'` event on client sockets of worker logger.
Fixes #713
=> fix(#713): handle unexpected hangups in multiprocess appender

types/log4js.d.ts
Doing this allows for typescript and angular to use the class as a dependency injection object.
=> Making Logger def a class instead of interface.

lib/appenders/tcp-server.js, lib/appenders/tcp.js, test/tap/server-test.js, test/tap/tcp-appender-test.js
I've added a delimiter between log messages, which should make it handle multiple log messages arriving at the same time.
=> fix: #756 - handle multiple messages better

lib/appenders/tcp-server.js
This also fixes a potential concurrency issue by storing received data per socket connection instead of globally.
=> Fix duplicate log messages in TCP server (fixes #761)

lib/log4js.js, package-lock.json, package.json, test/tap/configuration-validation-test.js
pr #766 try to fix #743 use serialisation to copy input config.
but cause other issues (#774 #772 )
this pr uses `rfdc` deep-clone the input config return a new unfreeze config object.
temporary fix until 4.0 ?
=> fix: #743 and pr #766 cause other issues

lib/appenders/multiprocess.js
Delegate all serialisation tasks to LoggingEvent, instead of
maintaining a separate codepath in the multiprocess appender
=> refactor(multiprocess): serialisation consistency

lib/appenders/index.js
When using the experimental ES2015 support with Node.js (mjs modules) the main property of require is undefined causing the third check to fail to loading appenders to always fail. This simple fix will enable the fourth check to execute when loading mjs modules.
=> fix require.main for use with Node.js mjs modules

docs/noLogFilter.md, lib/appenders/noLogFilter.js, test/tap/noLogFilter-test.js, types/log4js.d.ts
Added the feature to exclude the log events depending on the regular expression provided in the configuration.
The feature works in a similar way to the categoryFilter and logLevelFilter appenders. The log events, which will match the regular expression, will be excluded and not passed to the appender.
The regular expressions can be configured through a string or an array of strings. 
The log events will be evaluated in case-insensitive mode.
=> FeatureRequest: nolog in general config #640

docs/connect-logger.md, lib/connect-logger.js, test/tap/connect-logger-test.js, types/log4js.d.ts
When using the `connectLogger` and the level set to `auto`, logging levels are set accordingly:
* http responses 3xx, level = `WARN`
* http responses 4xx & 5xx, level = `ERROR`
* else, level = `INFO`
This general grouping does not always work however as codes such as `304 Not Modified`, which in some cases are expected, are always returned as `WARN` and cannot be assigned to `INFO` without changing it for all other codes.
This feature aims to bring in some customisability around how those levels are set by passing in `statusRules` via the `options` object. An example would be:
```javascript
app.use(log4js.connectLogger(logger, { level: 'auto', statusRules: [
{ from: 200, to: 299, level: 'debug' }, // all 2xx are logged at DEBUG
{ codes: [304],  level: 'info' }        // 304 is logged at …
```
=> Feature - Add status code rulesets for connectLogger

lib/LoggingEvent.js, package-lock.json, package.json, test/tap/LoggingEvent-test.js, test/tap/multiprocess-test.js, test/tap/tcp-appender-test.js
CircularJSON is now deprecated, so replace it with its successor
and use it in the sole location where we used CircularJSON, ie
in the LoggingEvent serialization/deserialization functions
* npm - install flatted, remove circular-json
* LoggingEvent - use flatted for serialization/deserialization
* tests - acknowledge that flatted (and circular-json) should not
parse anything other than their respective serialized payloads
and use flatted when parsing/stringifying test data
Fixes #789
=> fix(#789): use flatted in place of CircularJSON

lib/connect-logger.js, test/tap/connect-logger-test.js, test/tap/connect-nolog-test.js
I started off just adding tests to cover cases which had been missed, but I also replaced the non-standard `res._headers` with `res.getHeader()`, and removed code which wasn't used.
=> Improve connect logger coverage

lib/appenders/console.js, lib/appenders/fileSync.js, lib/appenders/index.js, lib/appenders/noLogFilter.js, lib/categories.js, lib/clustering.js, lib/configuration.js, lib/connect-logger.js, lib/layouts.js, lib/log4js.js, package-lock.json, package.json, test/tap/configuration-validation-test.js, test/tap/connect-logger-test.js, test/tap/connect-nolog-test.js, test/tap/dateFileAppender-test.js, test/tap/fileAppender-test.js, test/tap/fileSyncAppender-test.js, test/tap/layouts-test.js, test/tap/logger-test.js, test/tap/multi-file-appender-test.js, test/tap/multiprocess-shutdown-test.js, test/tap/multiprocess-test.js, test/tap/newLevel-test.js, test/tap/stderrAppender-test.js, test/tap/stdoutAppender-test.js
I noticed that several of the dependencies are out-of-date. This PR updates the dependencies and fixes linting errors that were an issue after the update.
=> Updating dependencies (including eslint)

examples/log-rolling-bug.js, package-lock.json, package.json
This is a fix for #842 - new steamroller version picks up the initial size of files when appending.
(Update to tap version fixes a few npm audit vulnerabilities)
=> fix: updated streamroller to fix log rolling when appending

lib/layouts.js
Fixes #859
I would add tests for node v12, but there are a number of unrelated failures. I'll take a stab at getting the tests to pass under node v12 on a different PR. This one can solve the immediate problem that will stop log4js users from upgrading to node v12.
=> fix(layout): Use level as a string for node v12

types/log4js.d.ts
per https://github.com/log4js-node/log4js-node/blob/master/docs/layouts.md
You can add your own layouts by calling `log4js.addLayout(type, fn)` before calling `log4js.configure`. `type` is the label you want to use to refer to your layout in appender configuration. `fn` is a function that takes a single object argument, which will contain the configuration for the layout instance, and returns a layout function. A layout function takes a log event argument and **returns a string (usually, although you could return anything as long as the appender knows what to do with it).**
=> Allow anything in the addLayout

docs/connect-logger.md, lib/connect-logger.js, test/tap/connect-context-test.js
Proposing a way to use a response of express in custom layouts or appenders.
In this version, `connectLogger` adds a response of express to context if `context` flag is set to `true`, and we can use it in custom layouts or appenders.
=> feat(connectLogger): add response to context

lib/appenders/file.js, test/tap/file-sighup-test.js
The streamroller upgrade in version 4 removed a couple of functions that the signup handler used, but the test had mock versions so nothing broke. 
This PR fixes #847
=> Sighup handler was just nonsense

types/log4js.d.ts, types/test.ts
I sent PR #862.
But I forgot to add a type definition for TypeScript.
I'm sorry.
=> fix(connectLogger): type definition for context option.

docs/connect-logger.md, test/tap/connect-logger-test.js
@nomiddlename 
I add something to the docs explaining how to add the body token to a custom format. related to #868
=> docs: add explaining custom format

lib/LoggingEvent.js, lib/categories.js, lib/layouts.js, lib/log4js.js, lib/logger.js, package.json, test/tap/LoggingEvent-test.js, test/tap/configuration-validation-test.js, test/tap/layouts-test.js, test/tap/logger-test.js, test/tap/logging-test.js
- logger add `enableCallStack(boolean)`
- more layout support
- `%f` fileName
- `%l` lineNumber
- `%o` columnNumber
- `%s` call stack
=> add line number support

lib/appenders/index.js
This is a fix for #816 that got completely forgotten about as far as I can tell. Sorry.
=> fix: loglevelfilter was missing from core appenders

types/log4js.d.ts
add to enableCallStack to Configuration Interface
=> TS Configuration interface: add  enableCallStack

lib/appenders/index.js, test/tap/configuration-validation-test.js
This PR is related to issue https://github.com/log4js-node/log4js-node/issues/832.
It adds the ability to supply an appender instance (instead of just a string name) when specifying a configuration.
=> feature: adding the option to provide appender instance in config

CHANGELOG.md, docs/appenders.md, lib/appenders/index.js, types/log4js.d.ts, types/test.ts
Added some documentation that nobody will ever read, so that I can say "did you read the docs?" when they raise issues.
@kaxelson if you could take a quick look to confirm that it matches up with your pull request that would be great. I'll merge it anyway, so as not to delay the release - we can always fix up errors in the docs later.
=> Docs for appender passing

.travis.yml, package-lock.json, package.json, test/tap/configuration-test.js
This change upgrades streamroller and drops support for node v6 (which is end-of-life anyway).
=> chore: updated streamroller to v2, means we cannot support node v6

lib/clustering.js, package-lock.json, package.json, test/tap/no-cluster-test.js
This fixes the issue where errors are thrown when trying to use log4js in a browser (NUXT, Vue, webpack, etc). I have no idea if log4js will work, but at least it won't throw this particular error.
=> fix: handle cluster module not existing

package-lock.json, package.json
Streamroller 2.2.0 falls back to copy and truncate when a file is busy. This can happen if someone it tailing a log file, for instance, while we're trying to rename and delete it.
=> fix: updated streamroller to improve windows log rolling

examples/date-file-rolling.js, package-lock.json, package.json
This should help at least some of the problems in #836 - if the dateFile pattern is all digits, then streamroller was getting confused with the index part of the file name and not deleting old files.
=> fix: update streamroller to handle date patterns that are all digits

package-lock.json, package.json
Streamroller 2.2.2 includes this [change](https://github.com/log4js-node/streamroller/pull/54) which should fix the problem in #906 where date files overwrite the current log on restart.
=> fix: update streamroller to fix #906

docs/layouts.md, examples/stacktrace.js, lib/layouts.js, test/tap/layouts-test.js
This fixes the errors found in #955, and also adds negative truncation (allowing you to truncate fields from the end of the string instead of the start).
=> fix: truncation and padding for stacktraces

lib/appenders/file.js, test/tap/pause-test.js
Hi,
I made some change in file.js module, so when the buffer is full the 'pause' event will emit, and after now we can listen to this event. When this event is emitted we can stop logging or maybe send 'server too busy' response and wait till the drain event emitted. With these changes logger will not stop and just an event emitted, and this is possible if someone want to continue logging.
=> [enhancement]Emmit pause event for node js when buffer is full

docs/dateFile.md, docs/file.md
This fixes #963 - documents the pause/resume events for the file appenders.
=> docs: added pause/resume info for file appenders

.npmignore
We noticed that .bob was in our production container 
```
du -k node_modules/* | awk '$1 > 2000' | sort -nr 
2648	node_modules/log4js/.bob
2632	node_modules/log4js/.bob/complexity
2624	node_modules/log4js/.bob/complexity/plato
```
Since .bob is in the .gitignore and only referenced in the tests https://github.com/log4js-node/log4js-node/blob/5545f2a932e012177e553bfda90d8b3fba80b332/test/tap/LoggingEvent-test.js#L19 we figured you might want to add it to the .npmignore
=> Ignore .bob when publishing

package-lock.json, package.json
Streamroller 2.2.4 contains a fix for incorrect filename matching when cleaning up old files.
=> chore: update streamroller to 2.2.4

lib/appenders/file.js, test/tap/fileAppender-test.js
It's quite common for developers to use embedded color sequence like `\x1b[33m` in the log string to make the output look beautiful. 
However, if the output is also set to append to some file, the embedded color sequence will write to the given file as is, which may not be expected in some cases. 
Thus I added one more option for file appender, which is `removeColor`. It's a boolean value that controls whether if the appender should detect and remove embedded color sequence before writing to file.
When this option is set to `false`, everything will be written to file as is. For example,
```javascript
log4js.configure({
appenders: {
Core: { type: "file", filename: "app.log", removeColor: false },
console: { type: "console" }
},
categories: {
bot: { appenders: ["console", "Core"], level: …
```
=> Added support for removing embedded ANSI color sequence for file appender

lib/appenders/index.js, test/tap/configuration-validation-test.js
Related to #1000 . The fix will check if an appender exists in a category before trying to create it.
=> Donot create appender if not used

docs/categories.md
Noticed that the categories inheritance / hierarchy principle was described only in:
- [https://github.com/log4js-node/log4js-node/blob/master/docs/terms.md](url)
- and in the test files [https://github.com/log4js-node/log4js-node/blob/master/test/tap/configuration-inheritance-test.js](url)
Maybe it is worth to provide additional info on the appenders page and/or on a separate dedicated page.
=> Describe categories inheritance

types/log4js.d.ts
Sometimes it can be useful to know the category of the logger.
The category can be read from pure JavaScript code but TypeScript code cannot read it as the field is not declared.
This change adds the field to the TypeScript declaration. The access to it is read-only as changing the category of logger probably makes no sense.
=> Access to 'category' field of logger objects in TS

lib/appenders/index.js
Fixes issue #1008 (Problem using webpack with fileSync Appender).
This PR pre-loads the fileSync appender in lib/appenders/index.js so that Webpack can find it.
(This is based off of how issue #816 was fixed with PR #882 .)
=> fix: fileSync was missing from core appenders

docs/appenders.md
Relates to #1007.
It seems not good to add to optional appenders, so I've created new section for it.
=> Add section in documentation for links to other appenders

lib/appenders/file.js, test/tap/file-sighup-test.js
Fixes #437, Fixes #556, Fixes #700, Fixes #785, Fixes #852, Fixes #886
> _Originally posted by @nomiddlename in https://github.com/log4js-node/log4js-node/issues/852#issuecomment-496316399_
> I think the issue is that each file appender instance adds a SIGHUP handler, when they could all use the same handler. I'll see if I can work on a fix.
Implemented a fix based on @nomiddlename's comment, to create a single SIGHUP listener.
=> Avoid creating multiple SIGHUP listeners for File Appender

lib/logger.js, test/tap/newLevel-test.js
a warning is logged if the `log` method is used with an unknown log-level
this happens whenever people confuse the `log` method with yet another log-level-short method (like in the browser console.log)
adjusted `newLevel-test` accordingly
rel: https://github.com/log4js-node/log4js-node/issues/1042
Signed-off-by: abernh <a.bernhard@23go.de>
=> fix(logger.log): warn on invalid log-level

types/log4js.d.ts
The Typescript types are wrong for the File appender. This is related to https://github.com/log4js-node/log4js-node/pull/807
=> fix: file appender types

types/log4js.d.ts
Minor typedef improvement that better reflects the implementation, and also helps guide TypeScript developers using Logger.log.
=> fix(types): add level parameter declaration to Logger.log function

test/tap/configuration-test.js
`graceful-fs@4.2.5` broke it as it changed to use `Object.setPrototypeOf(read, fs$read)`.
```diff
-L136    read.__proto__ = fs$read
+L136    if (Object.setPrototypeOf) Object.setPrototypeOf(read, fs$read)
```
_(https://github.com/isaacs/node-graceful-fs/commit/c55c1b8cb32510f92bd33d7c833364ecd3964dea#diff-f740ecac46b2fdaa68156b133262813aa6f66218b11d8709bab83580e76e486dR136)_
When `fakeFS.read` is `undefined`, it now throws an error as `Object.setPrototypeOf` doesn't accept `undefined` in its parameters.
=> test: update fakeFS.read as graceful-fs uses it

package-lock.json, package.json, test/sandbox-coverage.js
`nyc@^15.0.0` broke `test/sandbox-coverage.js`, hence some changes were required.
```diff
@@ -48,8 +48,7 @@ function coverageFinder () {
=L48 L48   
=L49 L49   class NYC {
=L50 L50     constructor (config) {
-L51           config = config || {}
-L52           this.config = config
+    L51       this.config = { ...config }
=L53 L52   
=L54 L53       this.subprocessBin = config.subprocessBin || path.resolve(__dirname, './bin/nyc.js')
```
_(https://github.com/istanbuljs/nyc/pull/1195/files#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346)_
Thus, there is no more default `config={}`.
Existing code (below) resulted in `Cannot read property 'subprocessBin' of undefined`.
https://github.com/log4js-node/log4js-node/blob/eaf53f4c62ffd168eebc67e18de986910fba3d40/test/sandbox-cov …
=> chore(deps-dev): bump nyc from 14.1.1 to 15.1.0

lib/appenders/index.js, lib/categories.js, lib/log4js.js, test/tap/file-descriptor-leak-test.js, test/tap/logging-test.js
Fixes #788, Fixes #978, Fixes #1005, Fixes #1058
Additionally, this PR supersedes PR #1083
**Allow multiple configure() calls:**
Calling multiple `configure()` without `shutdown()` may leave resources open (file handles, network connections, etc).
This patch explicitly does a `shutdown() `for subsequently `configure()` to prevent resource leaks.
**Allow multiple shutdown() calls:**
Within the `shutdown()`, it now clears `appenders` and `categories`. Repeated/duplicated `shutdown()` calls will no longer traverse the same `appenders` to shut them down them again which will result in `Error [ERR_STREAM_WRITE_AFTER_END]: write after end`.
=> Fixes file descriptor leak in certain use cases

test/tap/file-sighup-test.js
=> test: added assertion for increase of SIGHUP listeners on log4js.configure()

test/tap/configuration-validation-test.js
This leaves the following Untracked files.
`test/tap/freeze-date-file-test`
=> test(improvement): Add tearDown to unit tests

lib/appenders/index.js, types/log4js.d.ts
This is much like the fix for #1008 and #816 
I've also included typescript typings for the TCP appender. I can remove these if you prefer.
There are some other core appenders that are also not in this list, however I'm unsure if this was intentional or by accident so have only included the one I'm currently concerned with and tested for now.
=> Fix TCP appender with Webpack and Typescript

lib/log4js.js, types/log4js.d.ts, types/test.ts
Resolves  log4js-node/log4js-node#967.
=> Expose recording in typescript

lib/appenders/dateFile.js, lib/appenders/file.js
Make the same that "file" appender does
=> dateFile error handling fix

lib/appenders/dateFile.js, lib/appenders/file.js
=> chore(refactor): using writer.writable instead of alive for checking

lib/appenders/file.js, lib/appenders/fileSync.js, test/tap/fileAppender-test.js, test/tap/fileSyncAppender-test.js
Related to https://github.com/log4js-node/streamroller/issues/59, https://github.com/log4js-node/streamroller/pull/74 and https://github.com/log4js-node/log4js-node/pull/1135
**Important**
It is also to note the file does not roll within itself (truncate its older entry for newer entry).
It truncates all and appends only the new entry.
```javascript
var rollers = require('streamroller');
var stream = new rollers.RollingFileStream('myfile', 6, 0);
stream.write("abc"); // add as first row
stream.write("def"); // add as second row
stream.write("ghi"); // truncate all and add as first row
stream.end();
```
Output:
```
myfile   - ghi
```
=> allow for zero backup - https://github.com/log4js-node/streamroller/pull/74

.github/workflows/node.js.yml
This adds the `typings` step to the build, so that we will know if a typescript change breaks things.
=> Add step to run typescript tests

types/log4js.d.ts, types/test.ts
Fixes v6.4.0 regressions.
There is an npm script `npm run typings` which actually failed before
this commit. This seems to have been a combination of incorrect typings
(a mandatory argument to `getLevel` that should be optional, the idea
that for custom appenders `configure` should return an intermediate
"generator" function before the appender function itself) as well as
mistakes in the test file (which had an appender module which had one
level of function nesting too few).
Specifically, for the `configure` function on appenders, I believe there
should be two levels of function: an outer function taking one-time
configuration, and an inner function taking an individual log messages.
The typings file wanted there to be three layers, and the test file
wanted there to be one layer.
Fixes …
=> Make typings match code better

.github/workflows/npm-publish.yml
To avoid accidentally publishing broken typescript definitions to NPM in future.
=> Add types check to publish workflow

docs/layouts.md, lib/layouts.js, test/tap/layouts-test.js
=> refactor date pattern names for clarity (when %date actually means %datetime)

lib/LoggingEvent.js, test/tap/LoggingEvent-test.js
Fixes #1187 
Only affects clustering, multiprocessAppender, and tcpAppender.
These three will `serialise()` to `String` to transmit for the receiver to `deserialise()`.
Due to `JSON.stringify()`, there are some translation loss:
| Code | Object | JSON.stringify() | Fix |
|-|-|-|-|
`{"a": parseInt("abc")}` | `{"a": NaN}` | `{"a": null}` | `{"a": "NaN"}` | 
`{"b": 1/0}` | `{"b": Infinity}` | `{"b": null}` | `{"c": "Infinity"}` |
`{"c": -1/0}` | `{"c": -Infinity}` | `{"c": null}` | `{"c": "-Infinity"}` |
`[undefined]` | `[undefined]` | `[null]` | `["undefined"]` |
While the fix parses them to `String` instead of the `Object`, it does not affect the output in log files.
=> Fixes serialise() for NaN, Infinity, -Infinity and undefined

test/tap/dateFileAppender-test.js, test/tap/fileSyncAppender-test.js, test/tap/multi-file-appender-test.js, test/tap/pause-test.js, test/tap/tcp-appender-test.js
- https://github.com/log4js-node/log4js-node/pull/1200
- https://github.com/log4js-node/log4js-node/pull/1204
| File                | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
| --------------------|---------|----------|---------|---------|-------------------
| All files           |   98.62 -> 99.48 |    97.91 -> 98.67 |   98.51 -> 100 |   98.56 -> 99.46 |
=> chore(test): improve test coverage

lib/categories.js, lib/logger.js, test/tap/logger-test.js
=> chore(fix): set logger.level on runtime will no longer reset useCallStack

package-lock.json, package.json
Path: nyc [dev] > istanbul-lib-instrument > @babel/core > json5 > minimist
* Fix: Removed dependence on minimist to patch CVE-2021-44906. (https://github.com/json5/json5/issues/266)
=> chore(dep): updated dependencies

lib/appenders/adapters.js, lib/appenders/fileSync.js, lib/appenders/multiprocess.js, lib/categories.js, lib/layouts.js, test/tap/layouts-test.js, test/tap/multiprocess-test.js, test/tap/tcp-appender-test.js
[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) which works similarily but isn't deprecated. While [String.prototype.substring()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substring) isn't deprecated I replaced it with `slice()` as well.  `slice()` is generally a bit faster (and uses less bites as the name is shorter) and this way we don't have 2 functions which nearly do the same thing in the code.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.
=> refactor: replace deprecated String.prototype.substr()

lib/appenders/file.js, lib/appenders/fileSync.js
1. `~` in `~/` or `~\` will be expanded to `os.homedir()`
(`~` and `~filename` unaffected as these are valid filenames)
=> feat: tilde expansion for filename

lib/logger.js, test/tap/newLevel-test.js
1. `logger.log()` will behave as a synonym for `logger.info()` as much as possible based on the method signature
2. No regression for `logger.log()`'s existing private function (which has a different method signature)
3. If it is unable to determine if it should be a synonym from the method signature, it will `WARN` and fallback to `INFO`
=> feat: `logger.log()` to be synonym of `logger.info()`

lib/appenders/fileSync.js
Strangely, `fs.appendFileSync` uses `flag` but `fs.createWriteStream` uses `flags`.
It's somewhat inconsistent throughout the Node.js documentation:
https://nodejs.org/api/fs.html
=> fix: fs.appendFileSync should use flag instead of flags

.editorconfig, .gitattributes, package.json, types/log4js.d.ts, types/test.ts
Appender was a discriminated type union, which unfortunately made it so that it wasn't able to be modified. Now you can update the `Appenders` interface with new values to enable modification.
```ts
declare module './log4js' {
interface Appenders {
StorageTestAppender: {
type: 'storageTest';
storageMedium: 'dvd' | 'usb' | 'hdd';
};
}
}
```
------
Most of the changes in this PR are prettier being run, as I also set up the editorconfig to apply properly to typescript files as well.
The gitattributes was also missing typescript files.
=> Make Appender Type extensible from other modules and the user

types/log4js.d.ts
=> fix: Logger has not export in entry file

lib/LoggingEvent.js, lib/connect-logger.js, lib/logger.js, test/tap/LoggingEvent-test.js, test/tap/logLevelFilter-test.js
Fixes #1187
Supersedes PR #1188
Only affects clustering, multiprocessAppender, and tcpAppender.
These three will `serialise()` to `String` to transmit for the receiver to `deserialise()`.
| Code | Object<br>(Input) | Serialised<br>(Transmission) | Deserialised<br>(Output) | Match
|-|-|-|-|-|
`{"a": Number("abc")}` | `{"a": NaN}` | `{"a": "__LOG4JS_NaN__"}` | `{"a": NaN}` | ✔️ |
`{"b": 1/0}` | `{"b": Infinity}` |  `{"b": "__LOG4JS_Infinity__"}` | `{"b": Infinity}` | ✔️ |
`{"c": -1/0}` | `{"c": -Infinity}` | `{"c": "__LOG4JS_-Infinity__"}` | `{"c": -Infinity}` | ✔️ |
`[undefined]` | `[undefined]` | `["__LOG4JS_undefined__"]` | `[undefined]` | ✔️ |
Compared to PR #1188, now the output matches exactly the input.
=> fix(LoggingEvent): serde for `NaN`, `Infinity`, `-Infinity`, `undefined`

lib/appenders/file.js, lib/appenders/fileSync.js, lib/logger.js, test/tap/fileAppender-test.js, test/tap/fileSyncAppender-test.js
Fixes log4js-node/streamroller#164
1. `~` in `~/` or `~\` will be expanded to `os.homedir()`
(`~` and `~filename` unaffected as these are valid filenames)
=> fix: tilde expansion for windows

lib/clusteringBrowser.js, package.json
Certain modules do not exist in a browser environment, e.g. cluster, file/os/path, etc.
In that environment, file-based appenders are effectively disabled by this commit, without modifying the source directly.
The `clustering.js` file is still required, but this commit essentially makes it a no-op, again without modifying the source directly.
This addresses #968 and supersedes PR 1023 https://github.com/log4js-node/log4js-node/pull/1023
=> Idempotent logging on browser

lib/logger.js
Regression since [6.8.0](https://github.com/log4js-node/log4js-node/milestone/92) from #1363 at commit 7922e82.
=> fix(7922e82): regex for stacktrace

lib/connect-logger.js, test/tap/connect-context-test.js, test/tap/connect-logger-test.js, test/tap/connect-nolog-test.js
writeHead now also returns a reference to the response object as specified here: https://nodejs.org/api/http.html#responsewriteheadstatuscode-statusmessage-headers
=> fix: enable method chaining for after writeHead

docs/file.md
Add `removeColor` option of file appender (merged in #1001), which is missing in the docs.
=> docs(file): add `removeColor` option of file appender
