- lib/appenders/smtp.js
- test/smtpAppender-test.js
I made as few as possible modifications. So every configuration which was working before should be working now. However, this is not compatible with the pre 1.0.0 releases of nodemailer.
> The smtp appender now works with the current version of nodemailer - fixes #287 

- lib/appenders/smtp.js
> make sure to call require()

- lib/connect-logger.js
I just stumbled on this issue in my project and found out there was already a fix available :). 
Is this fix ok? Will you consider merging it in log4js-node?
> Use x-forwarded-for if available for :remote-addr

- lib/layouts.js
- test/layouts-test.js
Just a simple hook to add layoutMakers I then wrote a small repo to be able to log as json (https://github.com/gabe0x02/log4js-json-layout).  Let me know what you think.
> hook to add cusotm layouts

- lib/appenders/logstashUDP.js
- lib/layouts.js
- test/logstashUDP-test.js
Extending log message with extra fields will allow to reduce parsing on logstash side.
> extra json data fields for logstash

- lib/appenders/logstashUDP.js
- lib/connect-logger.js
- package.json
Hi, I noticed that `package.json` was referring to `underscore` twice.
Given that there are only 2 places where it is used, I ventured into removing it all together.
I hope this helps.
Thanks for your attention!
> Remove the underscore dependency

- lib/appenders/smtp.js
- test/smtpAppender-test.js
This pull request implements a new feature : 
- allow to send logs as a file attachment;
- customized email message;
- customize attachment filename
Best regards,
> Send logs as email attachment

- lib/appenders/dateFile.js
- lib/appenders/file.js
- lib/appenders/smtp.js
- lib/log4js.js
- lib/streams/DateRollingFileStream.js
- lib/streams/RollingFileStream.js
- package.json
- test/logging-test.js
- test/streams/rollingFileStream-test.js
Hi, here is what it could look like if we were to replace async by native recursions.
I did this as a small exercise. I find it mostly more readable but it really is a matter of taste.
I also spotted that the shutdown test in logging-test.js is written as a synchronous test although it tests an asynchronous behaviour.
Thanks for your patience and attention!
> Replace async by native recursions

- examples/hipchat-appender.js
- lib/appenders/hipchat.js
- test/hipchatAppender-test.js
@nomiddlename 
Here is a hipchat appender that I have added to log to a hipchat room using the [hipchat-client](https://github.com/germanrcuriel/hipchat-client) library.  
Please let me know what you think.  I based a lot of the tests and examples around mailgun and loggly, trying to keep with what seemed like best practices.  I would love to hear any suggestions you have.
> Hipchat connection

- lib/levels.js
- lib/logger.js
Allow V8 to optimize the logging functions by **not [leaking the arguments object](https://github.com/petkaantonov/bluebird/wiki/Optimization-killers#32-leaking-arguments)** and reducing the number of object accesses in the `toLevel` function.
This results in a performance improvement of about 11%.
before: 9,123 ops/sec ±1.46% (85 runs sampled)
after: 10,159 ops/sec ±1.97% (84 runs sampled)
```js
'use strict';
const Benchmark = require('benchmark');
const log4js = require('log4js');
log4js.configure({
appenders: [
{type: 'file', filename: 'log4jsbench.log', category: 'bench'},
],
levels: {
bench: 'debug',
},
});
const logger = log4js.getLogger('bench');
const data = {a: 'thing', num: 2};
new Benchmark.Suite()
.add('log', function() {
logger.info('message', data);
logger.trace('message', …
```
> Improve logging performance

- lib/appenders/categoryFilter.js
https://github.com/nomiddlename/log4js-node/issues/351
> Make categoryFilter respect cwd option

- examples/slack-appender.js
- lib/appenders/slack.js
- package.json
- test/mailgunAppender-test.js
- test/slackAppender-test.js
Hi, 
This is in order to add an appender for Slack (much like the existing Hipchat appender). 
I created an appender, sample file and a test. 
It's useful in order to alert errors to your team's Slack.
> Adding slack appender

- examples/memory-test.js
> update module location

- lib/layouts.js
- test/tap/layouts-test.js
> Add support for MDC in pattern layout

- docs/appenders.md
- docs/multiFile.md
- lib/appenders/multiFile.js
- test/tap/multi-file-appender-test.js
This PR addresses #437 - it lets you output to multiple files dynamically, based on properties of the logging event.
> Multi file appender

- docs/api.md
Improved documentation to fix confusion like in #265.
> clarify pm2-intercom is a pm2 module

- docs/api.md
- docs/faq.md
- lib/configuration.js
- lib/log4js.js
- lib/logger.js
- test/tap/disable-cluster-test.js
Here's the change to turn off the transparent support for clustering, just in case it causes weirdness for you.
> fix(cluster): add flag to turn off the cluster support

- lib/appenders/fileSync.js
- test/tap/fileSyncAppender-test.js
> fix(fileSync): options not used

- .eslintrc
- lib/appenders/file.js
- lib/appenders/gelf.js
- lib/appenders/logFaces-HTTP.js
- lib/appenders/logFaces-UDP.js
- lib/appenders/logstashUDP.js
- lib/appenders/smtp.js
- package-lock.json
- package.json
- test/tap/layouts-test.js
- test/tap/multiprocess-shutdown-test.js
- test/tap/pm2-support-test.js
There is a timing issue in the pm2 tests. I don't think these failures are different than past failures, it seems that the new tap version is simply more verbose, so there is a better explanation of these errors.
I did fix the issues with node 4 and node 5, these were related to the layout tests.
> chore: upgraded dev deps

- docs/appenders.md
- docs/rabbitmq.md
- examples/rabbitmq-appender.js
- lib/appenders/rabbitmq.js
- package.json
- test/tap/rabbitmqAppender-test.js
Added ability to push message to rabbitmq
> add rabbitmq appender to push to rabbitmq

- README.md
- docs/logstashHTTP.md
- examples/logstashHTTP.js
- lib/appenders/logstashHTTP.js
- package-lock.json
- test/tap/logstashHTTP-test.js
Hello, I needed to create a appender for logstash using HTTP , so I took the opportunity to add tests, comments and use cases and send them to you too.
Hope it can be helpful
> feat(logstash): add new logstashHTTP

- docs/webpack.md
documentation of webpack workaround
> docs: webpack workaround doc

- docs/logstashHTTP.md
- package-lock.json
- package.json
fix #702 - broken logstashUDP link
> fix(#706): fixes security vulns

- docs/multiFile.md
- lib/appenders/multiFile.js
- test/tap/multi-file-appender-test.js
added timeout as per suggestion in #691
> added timeout support to multiFile appender

- lib/layouts.js
- test/tap/layouts-test.js
> fix(#730): make the red color lighter for error

- lib/log4js.js
- test/tap/passenger-test.js
Copied over a test I'd written in the version-3.x branch for the passenger problem.
> fix: #525 disableClustering broken on passenger

- types/log4js.d.ts
- types/test.ts
> fix(typings): correctly type the `levels` property

- lib/layouts.js
- package-lock.json
- package.json
- test/tap/layouts-test.js
> fix: removed the custom inspect thing as it was only need for node < 6

- lib/log4js.js
- package-lock.json
- package.json
- fixed #734 by copy the input config, then pass into internal appenders setting.
- patch update `cirular-json`
> fix: #734 and patch update circular-json deps

- README.md
> Change for good cheese

- CHANGELOG.md
- examples/date-file-rolling.js
- package-lock.json
- package.json
There was a crashing bug in the previous version of streamroller. https://github.com/log4js-node/streamroller/pull/33
> fix: updated streamroller dep to fix bug

- types/log4js.d.ts
> Add missing types for Level

- README.md
- docs/connect-logger.md
- docs/recording.md
I saw #874 and found some errors related module name in document.
So, I'll fix them.
> fix(doc): name of required/imported module in document.

- package-lock.json
- package.json
> fix: updated streamroller should fix log rotation bug

- docs/layouts.md
- lib/layouts.js
- test/tap/layouts-test.js
solved #888 without using the token way, that i personnally found less clear.
> feat: add delimiter for fileName depth to %f layout patern

- package-lock.json
- package.json
> chore(deps): streamroller 1.0.5 -> 1.0.6

- lib/layouts.js
- package-lock.json
- package.json
- test/tap/configuration-validation-test.js
- test/tap/dateFileAppender-test.js
- test/tap/file-sighup-test.js
- test/tap/fileAppender-test.js
- test/tap/fileSyncAppender-test.js
- test/tap/layouts-test.js
- test/tap/multi-file-appender-test.js
- test/tap/multiprocess-shutdown-test.js
I wanted to make sure everything works on Windows, so the first step is to get the tests passing. Which they do, once I've corrected a few file paths mostly.
> chore: changes to get tests passing on windows

- package-lock.json
- package.json
The new version of date-format fixes the output of time when the timezone offset is specified. As this could do weird things if people are parsing the dates in their log output, this will be a breaking change.
> chore(deps): updated date-format to 3.0.0

- lib/appenders/dateFile.js
- test/tap/pause-test.js
Hi, I also add log4js:pause event to dateFile appender and add the test for that, please kindly review the code.
> fix: Add pause event to dateFile logger

- lib/log4js.js
- types/test.ts
> fix: Adds guards for undefiend callback functions in shutdown method

- lib/appenders/index.js
- test/tap/appender-dependencies-test.js
> fix: Allow appenders to depend on not-yet-loaded appenders.

- docs/tcp.md
- lib/appenders/tcp.js
- test/tap/tcp-appender-test.js
Related to #809 : enables to define a custom EndMessage string and to use a customized serializer of logs.
> feat: TCP appender - enabling a custom EndMsg token and a custom Layout

- lib/LoggingEvent.js
- lib/appenders/noLogFilter.js
- lib/categories.js
- lib/connect-logger.js
- lib/levels.js
ref. https://jsdoc.app/tags-param.html
> style: conform @param to official style

- README.md
- docs/index.md
PR to add the InfluxDB appender that I made to the list of available appenders. [https://github.com/rnd-debug/log4js-influxdb-appender](url)
See #1013
> docs: adding mention of InfluxDB appender

- README.md
- types/log4js.d.ts
- types/test.ts
The JavaScript code was indented with spaces, so I adjusted it.
> style(indentation): change indentation to soft tabs

- types/log4js.d.ts
> fix(types): logger _log() types

- types/log4js.d.ts
> fix(types): logger level types

- package-lock.json
- package.json
> chore(deps): bump streamroller from 3.0.1 to 3.0.2

- lib/appenders/index.js
> fix(multiprocess): startup multiprocess even when no direct appenders

- lib/appenders/index.js
> fixed eslint

- test/multiprocess-worker.js
- test/tap/multiprocess-test.js
Prevent regression for the multiprocess appender.
Regression like #1161.
> test(multiprocess): add e2e test

- types/log4js.d.ts
> fix(types): Logger constructor

- lib/connect-logger.js
> fix: connectLogger not logging on close

- lib/appenders/dateFile.js
- lib/appenders/file.js
- lib/appenders/index.js
- lib/appenders/logLevelFilter.js
> Defensive coding

- lib/appenders/fileSync.js
- lib/appenders/index.js
- lib/appenders/multiFile.js
- test/tap/configuration-validation-test.js
- test/tap/default-settings-test.js
- test/tap/file-descriptor-leak-test.js
- test/tap/file-sighup-test.js
- test/tap/fileAppender-test.js
- test/tap/fileSyncAppender-test.js
- test/tap/logging-test.js
- test/tap/multi-file-appender-test.js
- test/tap/multiprocess-test.js
- test/tap/recordingAppender-test.js
- test/tap/server-test.js
- types/test.ts
| File                | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
| --------------------|---------|----------|---------|---------|-------------------
| All files           |   97.67 -> 98.62 |    96.24 -> 97.91 |   97.42 -> 98.51 |   97.67 -> 98.56 |
> chore(test): improve test coverage

- docs/writing-appenders.md
Update Loading mechanism instruction (number 1 in priority) to match the current behaviour of the library.
> Update Loading mechanism instruction #1

- lib/layouts.js
Fixes #1060
Supersedes PR #1061
> chore(fix): fileDepth for ESM

- docs/connect-logger.md
- docs/file.md
- docs/fileSync.md
- types/log4js.d.ts
Fixes #1239 
- based on https://github.com/log4js-node/log4js-node/commit/faef3d20f643a9e1a29883f493cdbe893a47de77
- based on https://github.com/log4js-node/log4js-node/commit/d894f573058d50f6c41e9048f46fadc037097b16
- based on https://github.com/log4js-node/log4js-node/commit/e2947474c719d891b282858a4509fa8292f7ac22
- based on https://github.com/log4js-node/log4js-node/pull/1182
- based on https://github.com/log4js-node/log4js-node/pull/1181
> chore(docs): updated comments in typescript def

- lib/layouts.js
- lib/logger.js
- test/tap/newLevel-test.js
Related to PR #1062 (which fixes #1042)
Before Patch:
After Patch:
> fix: fallback for logger.log outputs nothing

- lib/appenders/file.js
- lib/appenders/fileSync.js
> fix: better file validation

- lib/appenders/file.js
- lib/appenders/fileSync.js
Reverts log4js-node/log4js-node#1249
> Revert "fix: better file validation"

- types/log4js.d.ts
expose `LogEvent.serialise` in types
> fix(types): add LogEvent.serialise

- test/sandbox-coverage.js
- test/tap/layouts-test.js
Reverts log4js-node/log4js-node#1293
> Revert "test: support older Node.js versions"

- package.json
Reverts log4js-node/log4js-node#1298
> Revert "chore(deps-dev): bump eslint from 8.16.0 to 8.20.0"

- types/log4js.d.ts
> type: corrected AppenderModule interface and Recording interface

- types/log4js.d.ts
- types/test.ts
> type: updated Configuration.levels type to allow for custom log levels

- docs/layouts.md
- lib/layouts.js
- test/tap/layouts-test.js
PR proposal to implement #1341
> feat issue #1341 (Layouts) : support a specifier on %m

- README.md
Fixes #1360
Related to #1229 (which fixes #1009 and fixes #1063)
> docs: updated typescript usage

- docs/api.md
> docs: added `log4js.isConfigured()`

- lib/LoggingEvent.js
- test/tap/LoggingEvent-test.js
> fix(LoggingEvent): serde for object with null prototype

- types/log4js.d.ts
Add missing typedef of `removeColor` option of file appender
> Add missing typedef of `removeColor` option of file appender
